Fix ignoring return value of ‘ftruncate’
This patch fixes warning being treated as error:
"src/storage.c:79:2: error: ignoring return value of ‘ftruncate’,
declared with attribute warn_unused_result [-Werror=unused-result]"